version: '2'

services:

  library-api-db:
    image: postgres:16.4
    container_name: library-api-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - library-api-db:/var/lib/postgresql/data

volumes:
  library-api-db: