spring:
  messages:
    basename: i18n/bundle
    encoding: utf-8
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql:library-api"
    username: "postgres"
    password: "password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  hibernate:
    format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
app:
  locale: ru_RU