spring:
  messages:
    basename: i18n/bundle
    encoding: utf-8
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    schema: classpath:/schema.sql
    data: classpath:/data.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  hibernate:
    format_sql: true
  h2:
    console:
      enabled: true
app:
  locale: ru_RU