spring:
  messages:
    basename: i18n/bundle
    encoding: utf-8
  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  hibernate:
    format_sql: true
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
app:
  locale: ru_RU